DSND-541:Write Data to company_mortgages collection
companieshouse/charges-data-api pull request #12
Opened 2022-03-17 13:27 UTC by adeshpandech

DSND-541:Transform and Write Data coming from consumer in to company_mortgages collection.

2022-03-18 08:19 UTC, zahidm3 commented on src/main/java/uk/gov/companieshouse/charges/data/converter/CompanyChargesReaderConverter.java
> +public class CompanyChargesReaderConverter implements Converter<Document, ChargeApi> {
cosmetic: maybe name like ReadConverter or ReadingConverter looks more appropriate

2022-03-18 08:20 UTC, zahidm3 commented on src/main/java/uk/gov/companieshouse/charges/data/model/ChargesDocument.java
> +@Document(collection = "company-mortgages")
Please externalise the collection name in applicatio yml so that we can override name using an env variable

2022-03-18 08:22 UTC, zahidm3 commented on src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
> +        List<ChargesDocument> chargesCollection = this.chargesRepository.findAll();
I guess fetching all done only for local testing purposes, we can remove this

2022-03-18 08:24 UTC, zahidm3 requested changes

2022-03-18 08:24 UTC, zahidm3 commented on src/itest/java/uk/gov/companieshouse/charges/data/repository/RepositoryITest.java
> +    externalData.setId(chargeId);
ChargeAPI object can be de-serialised from a valid json file to make the test more comphrehensive

2022-03-18 09:26 UTC, gseregni-ch requested changes

2022-03-18 09:26 UTC, gseregni-ch commented on src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
>      public void upsertCharges(String companyNumber, String chargeId,
I noticed that this method is not transactional and also the method in the controller where it's called. If I understood  properly we have a problem on local and rebel1 databases where transactional is not supported. In the Insolvency Data API project, two services classes have been created. So, not sure which approach we want to use here. @zahidm3 @adeshpandech Please let me know your thoughts.

2022-03-21 11:09 UTC, zahidm3 approved these changes

2022-03-21 11:16 UTC, gseregni-ch commented on src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
>      public void upsertCharges(String companyNumber, String chargeId,
I will mark this as resolved. As we discussed today in SU meeting we are going to handle the transactional in a separate story. Thanks.

2022-03-21 11:16 UTC, gseregni-ch approved these changes

2022-03-21 11:36 UTC, merged